// <auto-generated />
namespace WpfTestSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBrand4Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBrand4Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202107282017467_AddBrand4Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
